import type { ProductDatabase, Id } from './types'

export const productDatabase: ProductDatabase = {
  categories: [
    {
      _id: '1' as Id<'categories'>,
      name: 'Luxx Shades',
      description: 'Premium shades (formerly Curvers & Unishade)',
      _creationTime: 2342,
    },
    {
      _id: '2' as Id<'categories'>,
      name: 'Allusion Blinds',
      description: 'Modern allusion style blinds',
      _creationTime: 2342,
    },
    {
      _id: '3' as Id<'categories'>,
      name: 'Fabric Collections',
      description: 'Texstyle, Shaw, Alpha, Louvolite, Vertex Fabrics',
      _creationTime: 2342,
    },
    {
      _id: '4' as Id<'categories'>,
      name: 'Roller & Vertical',
      description: 'Roller and vertical blind components',
      _creationTime: 2342,
    },
    {
      _id: '5' as Id<'categories'>,
      name: 'Motors',
      description: 'Various motorization options',
      _creationTime: 2342,
    },
    {
      _id: '6' as Id<'categories'>,
      name: 'Panel Blinds',
      description: 'Panel blind systems',
      _creationTime: 2342,
    },
    {
      _id: '7' as Id<'categories'>,
      name: 'Cassette Blinds',
      description: 'Cassette style blinds',
      _creationTime: 2342,
    },
    {
      _id: '8' as Id<'categories'>,
      name: 'Plantation Shutters',
      description: 'Premium plantation shutters',
      _creationTime: 2342,
    },
    {
      _id: '9' as Id<'categories'>,
      name: 'Pleated Fly Screens',
      description: 'Pleated fly screen systems',
      _creationTime: 2342,
    },
    {
      _id: '10' as Id<'categories'>,
      name: 'Curtains',
      description: 'HOAD, Nettex, Charles Parsons',
      _creationTime: 2342,
    },
    {
      _id: '11' as Id<'categories'>,
      name: 'Combi & Venetian',
      description: 'Combination and venetian blinds',
      _creationTime: 2342,
    },
    {
      _id: '12' as Id<'categories'>,
      name: 'Roller Shutters',
      description: 'External roller shutters',
      _creationTime: 2342,
    },
    {
      _id: '13' as Id<'categories'>,
      name: 'EZIP & Outdoor',
      description: 'EZIP and outdoor blind systems',
      _creationTime: 2342,
    },
    {
      _id: '14' as Id<'categories'>,
      name: 'Specialty Items',
      description: 'Straight Drops, Wire Guides, PVC Blinds, Folding Arms',
      _creationTime: 2342,
    },
  ],
  products: [
    // Luxx Shades
    {
      _id: '1' as Id<'products'>,
      categoryId: '1' as Id<'categories'>,
      name: 'Luxx Premium Shade',
      priceType: 'sqm',
      basePrice: 85,
      minimumQty: 1,
      leadTime: '2-3 weeks',
      specialConditions: 'Import item',
      _creationTime: 2342,
    },
    {
      _id: '2' as Id<'products'>,
      categoryId: '1' as Id<'categories'>,
      name: 'Luxx Standard Shade',
      _creationTime: 2342,
      priceType: 'sqm',
      basePrice: 65,
      minimumQty: 1,
      leadTime: '1-2 weeks',
      specialConditions: '',
    },
    // Allusion Blinds
    {
      _id: '3' as Id<'products'>,
      _creationTime: 2342,
      categoryId: '2' as Id<'categories'>,
      name: 'Allusion Standard',
      priceType: 'sqm',
      basePrice: 75,
      minimumQty: 1,
      leadTime: '1-2 weeks',
      specialConditions: '',
    },
    {
      _id: '4' as Id<'products'>,
      categoryId: '2' as Id<'categories'>,
      name: 'Allusion Premium',
      _creationTime: 2342,
      priceType: 'sqm',
      basePrice: 95,
      minimumQty: 1,
      leadTime: '2-3 weeks',
      specialConditions: '',
    },
    // Fabric Collections
    {
      _id: '5' as Id<'products'>,
      _creationTime: 2342,
      categoryId: '3' as Id<'categories'>,
      name: 'Texstyle Collection',
      priceType: 'sqm',
      basePrice: 55,
      minimumQty: 1,
      leadTime: '1-2 weeks',
      specialConditions: '',
    },
    {
      _id: '6' as Id<'products'>,
      _creationTime: 2342,
      categoryId: '3' as Id<'categories'>,
      name: 'Shaw Fabrics',
      priceType: 'sqm',
      basePrice: 60,
      minimumQty: 1,
      leadTime: '1-2 weeks',
      specialConditions: '',
    },
    {
      _id: '7' as Id<'products'>,
      _creationTime: 2342,
      categoryId: '3' as Id<'categories'>,
      name: 'Vertex Fabrics',
      priceType: 'sqm',
      basePrice: 70,
      minimumQty: 1,
      leadTime: '3-4 weeks',
      specialConditions: 'No guarantee on timeframes',
    },
    // Combi & Venetian
    {
      _id: '8' as Id<'products'>,
      categoryId: '11' as Id<'categories'>,
      _creationTime: 2342,
      name: 'Combi Blind',
      priceType: 'sqm',
      basePrice: 70,
      minimumQty: 2,
      leadTime: '1-2 weeks',
      specialConditions: 'Minimum 2 sqm per blind',
    },
    {
      _id: '9' as Id<'products'>,
      categoryId: '11' as Id<'categories'>,
      name: 'Venetian Blind',
      _creationTime: 2342,
      priceType: 'sqm',
      basePrice: 70,
      minimumQty: 2,
      leadTime: '1-2 weeks',
      specialConditions: 'Minimum 2 sqm per blind',
    },
    // Roller Shutters
    {
      _id: '10' as Id<'products'>,
      _creationTime: 2342,
      categoryId: '12' as Id<'categories'>,
      name: 'Standard Roller Shutter',
      priceType: 'sqm',
      basePrice: 120,
      minimumQty: 1,
      leadTime: '2-3 weeks',
      specialConditions: '50% deposit required',
    },
    // Pleated Fly Screens
    {
      _id: '11' as Id<'products'>,
      _creationTime: 2342,
      categoryId: '9' as Id<'categories'>,
      name: 'Pleated Fly Screen',
      priceType: 'sqm',
      basePrice: 90,
      minimumQty: 1,
      leadTime: '2-3 weeks',
      specialConditions: '50% deposit required',
    },
    // Motors
    {
      _id: '12' as Id<'products'>,
      categoryId: '5' as Id<'categories'>,
      name: 'Standard Motor',
      priceType: 'each',
      basePrice: 350,
      minimumQty: 1,
      leadTime: '1-2 weeks',
      _creationTime: 2342,
      specialConditions: '',
    },
    {
      _id: '13' as Id<'products'>,
      categoryId: '5' as Id<'categories'>,
      name: 'Premium Motor',
      priceType: 'each',
      basePrice: 450,
      _creationTime: 2342,
      minimumQty: 1,
      leadTime: '2-3 weeks',
      specialConditions: '',
    },
    // Plantation Shutters
    {
      _id: '14' as Id<'products'>,
      categoryId: '8' as Id<'categories'>,
      name: 'Timber Plantation Shutter',
      priceType: 'sqm',
      _creationTime: 2342,
      basePrice: 180,
      minimumQty: 1,
      leadTime: '3-4 weeks',
      specialConditions: 'Custom fabrication',
    },
    {
      _id: '15' as Id<'products'>,
      categoryId: '8' as Id<'categories'>,
      name: 'PVC Plantation Shutter',
      priceType: 'sqm',
      basePrice: 140,
      minimumQty: 1,
      leadTime: '2-3 weeks',
      specialConditions: '',
      _creationTime: 2342,
    },
  ],
}

export const roomTypes = [
  'Living Room',
  'Bedroom',
  'Kitchen',
  'Bathroom',
  'Office',
  'Dining Room',
  'Study',
  'Laundry',
  'Other',
]

export const paymentTerms = [
  'Net 30 days',
  '50% deposit, balance on completion',
  'Full payment on order',
  'Net 14 days',
  'COD',
]

export const controlTypes = ['Cord', 'Chain', 'Motorized', 'Remote Control']

export const unitTypes = ['each', 'sqm', 'linear', 'hour']
